2021-05-10 17:49:05.188 -03:00 [INF] Starting web host
2021-05-10 17:49:06.714 -03:00 [INF] Now listening on: http://[::]:8000
2021-05-10 17:49:06.720 -03:00 [INF] Application started. Press Ctrl+C to shut down.
2021-05-10 17:49:06.721 -03:00 [INF] Hosting environment: Development
2021-05-10 17:49:06.722 -03:00 [INF] Content root path: C:\Users\felip\source\repos\FortalezaServer
2021-05-10 17:49:20.018 -03:00 [INF] Request starting HTTP/1.1 GET http://localhost:8000/api/fiscal/cfe-venda/2  
2021-05-10 17:49:20.095 -03:00 [INF] Executing endpoint 'FortalezaServer.Controllers.FiscalController.GetCfeVendaAsync (FortalezaServer)'
2021-05-10 17:49:20.166 -03:00 [INF] Route matched with {action = "GetCfeVenda", controller = "Fiscal"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.String]] GetCfeVendaAsync(Int32) on controller FortalezaServer.Controllers.FiscalController (FortalezaServer).
2021-05-10 17:49:21.470 -03:00 [INF] Entity Framework Core 3.1.10 initialized 'fortalezaitdbContext' using provider 'MySql.Data.EntityFrameworkCore' with options: None
2021-05-10 17:49:22.306 -03:00 [INF] Executed DbCommand (45ms) [Parameters=[@__id_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT `v`.`idvenda`, `v`.`aberta`, `v`.`acrescimo`, `v`.`desconto`, `v`.`descricao`, `v`.`hora_entrada`, `v`.`hora_fechamento`, `v`.`idcaixa`, `v`.`idcliente`, `v`.`idpdv`, `v`.`idresponsavel`, `v`.`numero_venda`, `v`.`paga`, `v`.`tipo`, `v`.`valor_pago`, `c`.`idcaixa`, `c`.`aberto`, `c`.`idnome_caixa`, `n`.`idnome_caixa`, `n`.`nome`
FROM `venda` AS `v`
INNER JOIN `caixa` AS `c` ON `v`.`idcaixa` = `c`.`idcaixa`
INNER JOIN `nome_caixa` AS `n` ON `c`.`idnome_caixa` = `n`.`idnome_caixa`
WHERE `v`.`idvenda` = @__id_0
LIMIT 1
2021-05-10 17:49:22.329 -03:00 [INF] Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ProblemDetails'.
2021-05-10 17:49:22.501 -03:00 [INF] Executed action FortalezaServer.Controllers.FiscalController.GetCfeVendaAsync (FortalezaServer) in 2326.3241ms
2021-05-10 17:49:22.503 -03:00 [INF] Executed endpoint 'FortalezaServer.Controllers.FiscalController.GetCfeVendaAsync (FortalezaServer)'
2021-05-10 17:49:22.509 -03:00 [INF] Request finished in 2495.4512ms 404 application/problem+json; charset=utf-8
2021-05-10 17:49:22.606 -03:00 [INF] Request starting HTTP/1.1 GET http://localhost:8000/favicon.ico  
2021-05-10 17:49:22.619 -03:00 [INF] Request finished in 13.5439ms 404 
2021-05-10 17:49:39.892 -03:00 [INF] Request starting HTTP/1.1 GET http://localhost:8000/api/fiscal/cfe-test  
2021-05-10 17:49:39.901 -03:00 [INF] Executing endpoint 'FortalezaServer.Controllers.FiscalController.GetCfeTestAsync (FortalezaServer)'
2021-05-10 17:49:39.906 -03:00 [INF] Route matched with {action = "GetCfeTest", controller = "Fiscal"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult`1[System.String] GetCfeTestAsync() on controller FortalezaServer.Controllers.FiscalController (FortalezaServer).
2021-05-10 17:50:43.951 -03:00 [INF] Request starting HTTP/1.1 GET http://localhost:8000/api/fiscal/cfe-venda/2  
2021-05-10 17:50:43.957 -03:00 [INF] Executed action FortalezaServer.Controllers.FiscalController.GetCfeTestAsync (FortalezaServer) in 64047.8615ms
2021-05-10 17:50:43.958 -03:00 [INF] Executing endpoint 'FortalezaServer.Controllers.FiscalController.GetCfeVendaAsync (FortalezaServer)'
2021-05-10 17:50:43.962 -03:00 [INF] Executed endpoint 'FortalezaServer.Controllers.FiscalController.GetCfeTestAsync (FortalezaServer)'
2021-05-10 17:50:43.965 -03:00 [INF] Route matched with {action = "GetCfeVenda", controller = "Fiscal"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.String]] GetCfeVendaAsync(Int32) on controller FortalezaServer.Controllers.FiscalController (FortalezaServer).
2021-05-10 17:50:43.969 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: This document already has a 'DocumentElement' node.
   at System.Xml.XmlDocument.IsValidChildType(XmlNodeType type)
   at System.Xml.XmlNode.AppendChild(XmlNode newChild)
   at FortalezaServer.Controllers.FiscalController.GerarCfe(Venda venda, InformacoesEmpresa informacoesEmpresa) in C:\Users\felip\source\repos\FortalezaServer\Controllers\FiscalController.cs:line 435
   at FortalezaServer.Controllers.FiscalController.GetCfeTestAsync() in C:\Users\felip\source\repos\FortalezaServer\Controllers\FiscalController.cs:line 511
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-05-10 17:50:44.016 -03:00 [INF] Entity Framework Core 3.1.10 initialized 'fortalezaitdbContext' using provider 'MySql.Data.EntityFrameworkCore' with options: None
2021-05-10 17:50:44.090 -03:00 [INF] Executed DbCommand (1ms) [Parameters=[@__id_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT `v`.`idvenda`, `v`.`aberta`, `v`.`acrescimo`, `v`.`desconto`, `v`.`descricao`, `v`.`hora_entrada`, `v`.`hora_fechamento`, `v`.`idcaixa`, `v`.`idcliente`, `v`.`idpdv`, `v`.`idresponsavel`, `v`.`numero_venda`, `v`.`paga`, `v`.`tipo`, `v`.`valor_pago`, `c`.`idcaixa`, `c`.`aberto`, `c`.`idnome_caixa`, `n`.`idnome_caixa`, `n`.`nome`
FROM `venda` AS `v`
INNER JOIN `caixa` AS `c` ON `v`.`idcaixa` = `c`.`idcaixa`
INNER JOIN `nome_caixa` AS `n` ON `c`.`idnome_caixa` = `n`.`idnome_caixa`
WHERE `v`.`idvenda` = @__id_0
LIMIT 1
2021-05-10 17:50:44.098 -03:00 [INF] Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ProblemDetails'.
2021-05-10 17:50:44.102 -03:00 [INF] Executed action FortalezaServer.Controllers.FiscalController.GetCfeVendaAsync (FortalezaServer) in 132.4707ms
2021-05-10 17:50:44.106 -03:00 [INF] Executed endpoint 'FortalezaServer.Controllers.FiscalController.GetCfeVendaAsync (FortalezaServer)'
2021-05-10 17:50:44.108 -03:00 [INF] Request finished in 157.3982ms 404 application/problem+json; charset=utf-8
2021-05-10 17:50:44.139 -03:00 [INF] Request finished in 64246.9804ms 500 text/html; charset=utf-8
